### ISSUE TITLE
Solution to auto execute tests and show results

### ISSUE THREAD

**Issue by DinisCruz** [jacogr/atom-lcov-info#11]
I really helps with TDD if we can have a mode with this workflow

a) make change in the code
b) change is picked up (by watcher or mocha)
c) code is instrumented 
d) tests execute
f) lcov data is reloaded 

All without user interaction

For reference that is the environment that I had when I was coding in C# with NCrunch (see [couple of my blog posts](http://blog.diniscruz.com/search/label/NCrunch) on that topic)

**Comment by DinisCruz** [comment]
Ok this is probably more complex that it needs to, but its working :)

see https://gist.github.com/DinisCruz/a6cb047a496461f6d7f6

the coffee script is executed using the 'Run in Atom' plugin

**Comment by jacogr** [comment]
The build is actually out of scope for the plugin. For instance in the workflow we typically use, gulp does exactly that. (Or grunt, or ...)

It works with this package, i.e. gulp picks up changes, tests are executed, plugin automagically sees there are new lcov.info data and displays it as such.

**Comment by DinisCruz** [comment]
>  plugin automagically sees there are new lcov.info data and displays it as such.

how does that happen, when I was running it (with a similar behind the scenes lcov re-generation) the ui (i.e. lcov mappings) would only change if:

a) I went into another file
b) the current editor lost and regained focus
