### ISSUE TITLE
Allow the config of the folder to find the lcov file

### ISSUE THREAD

**Issue by DinisCruz** [jacogr/atom-lcov-info#15]
for example I prefer to use **.coverage** instead of **coverage**

**Comment by jacogr** [comment]
Makes sense. +1

**Comment by DinisCruz** [comment]
For reference (namely mine) here is where the change needs to be made

![image](https://cloud.githubusercontent.com/assets/656739/5705612/87cc0dce-9a72-11e4-97f8-ce2f21f7d161.png)

**Comment by jacogr** [comment]
Fixed in https://github.com/jacogr/atom-lcov-info/commit/9bd06e00a3ae8bb268ecde61db5c1a99fbb93667
