### ISSUE TITLE
coverage circle is partially hidden (CSS issue)

### ISSUE THREAD

**Issue by DinisCruz** [jacogr/atom-lcov-info#16]
See 

![image](https://cloud.githubusercontent.com/assets/656739/5690930/d1162f44-98a3-11e4-94b4-4a6f8cf70709.png)

**Comment by jacogr** [comment]
Ouch. +1

**Comment by DinisCruz** [comment]
Making these changes

![image](https://cloud.githubusercontent.com/assets/656739/5705559/21b27596-9a72-11e4-8218-0e9829c3c6d9.png)

makes it look like this, which I quite like:

![image](https://cloud.githubusercontent.com/assets/656739/5705564/3272a86a-9a72-11e4-8c1c-abfb2d73829f.png)

**Comment by jacogr** [comment]
https://github.com/jacogr/atom-lcov-info/commit/14792f7b553eb39f02e974b6bc048e3035ee0abd
