### ISSUE TITLE
On v0.9.2 specs are failing (2 errors and 7 depreciations)

### ISSUE THREAD

**Issue by DinisCruz** [jacogr/atom-lcov-info#17]
There are 2 errors and 7 depreciations 
![image](https://cloud.githubusercontent.com/assets/656739/5691145/214b0b68-98b0-11e4-9fbf-6a9be4ee871b.png)

**Comment by DinisCruz** [comment]
btw, what is the login [behind this test](https://github.com/jacogr/atom-lcov-info/blob/master/spec/lcov-info-view-spec.coffee#L5)?

Since it is designed to fail:

```
LcovInfoView = require '../lib/lcov-info-view'

describe "LcovInfoView", ->
  it "has one valid test", ->
    expect("life").toBe "easy"
```

**Comment by jacogr** [comment]
These are all the default tests - the package currently doesn't have "real" tests.

(Yes, it is horrible, especially for something that shows tests coverage)

**Comment by DinisCruz** [comment]
yes I noticed where that test is created, once I started working on an extension.

Here is the fix :) https://github.com/o2platform/atom-coffee-repl/commit/c21e5a45ecda767c70cf525a765afdd41559aa2a
