### ISSUE TITLE
toggled off but still has visible gutter

### ISSUE THREAD

**Issue by deeperx** [jacogr/atom-lcov-info#43]
i think that it would be better if we keep gutter indicators intact and change visibility of the test coverage pane at the same time.

currently, both toggle together.

@Toff9 how can I add this feature to atom-lcov-info?

**Comment by deeperx** [comment]
ok, i've added it. if you care, you can pull it.

**Comment by fracarma** [comment]
I think there should be an option to choose this. Actually, I want the highlighting toggled with the status pane!
