### ISSUE TITLE
Completely hide coverage info

### ISSUE THREAD

**Issue by pabloppp** [jacogr/atom-lcov-info#47]
It's quite upsetting that there's no way to hide the coverage info completely.
It would be nice if there was a way to, not only closing the panel but also hiding the gutters or line highlights.

I know that's just the opposite of what was done in https://github.com/jacogr/atom-lcov-info/pull/44/files but I don't understand why would someone want to show the coverage info while he's working on something other than tests.

Also I'd like to raise https://github.com/jacogr/atom-lcov-info/issues/39 as I think being able to toggle the coverage info easily could improve a lot the workflow.

**Comment by pabloppp** [comment]
Any update on this? Otherwise I'll just close this issue

**Comment by rwtaggart** [comment]
@pabloppp Can we reopen this issue?
I would also like this feature, and probably won't use the plug-in without this.

**Comment by pabloppp** [comment]
@rwtaggart as sad as it is, this repo seems dead since last summer :(
I hope in the future maybe this starts being maintained again by the creator or by someone else, but for now it doesn't make any sense to keep asking for things.
Sorry
